spring.application.name=zentransfer

spring.security.user.name=admin
spring.security.user.password=admin123456

server.port=8086

alipay.appPrivateKeyPath=/home/fw/.ssh/cmw/private_key.txt
alipay.appPubCertPath=/home/fw/.ssh/cmw/appCertPublicKey_2021004137638718.crt
alipay.gatewayUrl=https://openapi.alipay.com/gateway.do
alipay.appId=2021004137638718
alipay.certPath=/home/fw/.ssh/cmw/alipayCertPublicKey_RSA2.crt
alipay.rootCertPath=/home/fw/.ssh/cmw/alipayRootCert.crt
alipay.format=json
alipay.signType=RSA2
alipay.charset=utf-8
app.url=https://g34f439790.vicp.fun/
spring.jpa.hibernate.ddl-auto=update

uorder.payeeId="2088641086367762"
uorder.url=https://api.udinghuo.cn
uorder.appKey=MNoxp97e
uorder.secret=a6c663c9c0fc68028657cea443e6f08bac78aa6b
uorder.token="!*g2JeoCJQl2M3q58inE2pz6uDO2Dl2VkXXOEoVkv0W657r6EVB5Xd4NER04wZoQI~ZJgCSe758GNg8x@MpRjB6A**-"
uorder.privateKey="MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3NG5PKZh6mwCFUW8sUIr9CHzNIEXbaqHmrJvwJhm1d7RmWAeq2wdcx5e4hO/fvGLCYtHtbptR3o77CfE+cdETFbnTnevXKw5ClJSwwjw9tRFAt8Lmelabb9Z9OpjCudpxwPbu77uK0p2VF/dI0K0YIBUQlo1RG/bB5QMgvv1apuoQXYD/xT0AQ/TwP35Vnba+D0dH8q+C0X6KKpraCdYYnpRdS5zkJ1Ey8y0Ifb73dmlgplKAb9HpSpttpxGirN0/PxeD+bgbGnpeCokwN0tNj0xxec4uub/EDEDvfNzVZqmAhpl46UbNpJmDS61ZKuqJ2Mt/y85XcTtCZ4QO/9YdAgMBAAECggEACykqCS+PBvUXaIfH/oqflP+l3rc3GkFaQJvGWjBwA4KZ3lxBh1KVlbzhDNAobthiqdXsVQsWcjvdOQTnifbUFlYN/orR2cdZNIwprMUAd3/m36ryOCk+ynRbPEDMGpzI5oIraO343mGrUPBnU6vGx7/4mIybalQKSdCiSqXn+FQ1ZbM8zsJTxjfcs5X1ovs4xeZGmvZmawNXd+lwF7lFV3mfALNO0cS8fFAziPKJkPK7tqBvNXBDoKgEG9Ypis5unO9A2oY9nLNkf8A5l4d62mudOX7qi8ZfZFZa5x2WvlJbUOcv2KBjn9oCQUlg5XNwg8Axq5sDgNeVVhaOXletoQKBgQDjtuSXw8szIg/cRuwjZ5cNlp+bepI3sooPDJWmT+EA4ycQgn7W+NLIqFdGMPhGgDfcjtX2z7DWOWGdaIc5XWRc1GMvgfK0/SI6VoQrNgbYdfGhvw1hx8krzdIx46YFJdde8m7dPA1Y8RmT5qtlvfJaOQMJ7pWKbVioVn5srCvSbQKBgQDN9ixqRsW23IcSs5tIqMkGYIg6lSzTq9/JToYMB4X2mYdi4FONdN1RTHbqAZyVxQj3nuzOWHRHYtxHixYTAbv0jDXIy63wwBjwSWTf1iYqM09Vqp+3iewsz5xOwGb+a43GjAI0/PK9Zzn/yj0zxaWiauLwGWxwnZAdWJnn2O9EcQKBgQCwvuCnO32Y7rNI0nOu91SzY1n3ICgluxqVm7r8H7wRKD7F/cPdr7xLqv4yqQfMEPFK7EL/Ey262Ub/Gob665ZexytFUKPF/0R163ki4QhnMwSd+uC0KJHowhSITJ4sGLcWJy4N4fKqOlkUB1K54bkedmn5Z4oCq+TIpHn0d5578QKBgC9sSVnHJesu5+MEe/LE+lR/kZ57jrDGWGbPr8nBSbU4MJYxtMtTZ0o64v6KlHVfwurRKxFwCIYPW00V12VU9uQeDJxJWamfcZ6SJ6nqcyswWUoOWWw3U6wVuZXgc1aNiT14K2HsBDBcPlyJQoJTNgoptks2b2OWxAIdzoI1zxHhAoGAVRNeDqZ2jzBDD9z1JsvGD73R2BedLGu+GORBx46wKY+LVxcJ2V7aej1wqPWInSy7868AJzDnk4qqmZ324//L75teTDmmtExy2GIz0ddom1WJ7BOee51InuumDACYes/M4FvONxeWxBe3HDGRIkdLMVHrcM/d+MOFIfSjdsuhzZY="
uorder.publicKey="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtzRuTymYepsAhVFvLFCK/Qh8zSBF22qh5qyb8CYZtXe0ZlgHqtsHXMeXuITv37xiwmLR7W6bUd6O+wnxPnHRExW5053r1ysOQpSUsMI8PbURQLfC5npWm2/WfTqYwrnaccD27u+7itKdlRf3SNCtGCAVEJaNURv2weUDIL79WqbqEF2A/8U9AEP08D9+VZ22vg9HR/KvgtF+iiqa2gnWGJ6UXUuc5CdRMvMtCH2+93ZpYKZSgG/R6UqbbacRoqzdPz8Xg/m4Gxp6XgqJMDdLTY9McXnOLrm/xAxA73zc1WapgIaZeOlGzaSZg0utWSrqidjLf8vOV3E7QmeEDv/WHQIDAQAB"
