spring.application.name=zentransfer
server.port=8086

alipay.appPrivateKeyPath=/home/fw/.ssh/cmw/private_key.txt
alipay.appPubCertPath=/home/fw/.ssh/cmw/appCertPublicKey_2021004137638718.crt
alipay.gatewayUrl=https://openapi.alipay.com/gateway.do
alipay.appId=2021004137638718
alipay.certPath=/home/fw/.ssh/cmw/alipayCertPublicKey_RSA2.crt
alipay.rootCertPath=/home/fw/.ssh/cmw/alipayRootCert.crt
alipay.format=json
alipay.signType=RSA2
alipay.charset=utf-8
app.url=https://g34f439790.vicp.fun/
spring.jpa.hibernate.ddl-auto=update